/**
 * Re-exports from the auto-generated OpenAPI types.
 *
 * Usage in the frontend:
 *   import type { paths, components } from '@agent-builder/shared-types'
 *
 * The `api.d.ts` file is generated by running:
 *   cd packages/shared-types && npm run codegen
 */

import { components, paths } from './api.js'

// Auto-generated file — regenerate with: npm run codegen
// Source: FastAPI /openapi.json endpoint
export type { paths, components, operations, webhooks } from './api.js'

// ---------------------------------------------------------------------------
// Convenience type helpers
// ---------------------------------------------------------------------------

/** Extract the JSON request body type for a given path + method. */
export type RequestBody<
    P extends keyof paths,
    M extends keyof paths[P],
> = paths[P][M] extends {
    requestBody?: { content: { 'application/json': infer B } }
}
    ? B
    : never

/** Extract the 200 response body type for a given path + method. */
export type ResponseBody<
    P extends keyof paths,
    M extends keyof paths[P],
> = paths[P][M] extends {
    responses: { 200: { content: { 'application/json': infer R } } }
}
    ? R
    : never

/** Extract the 201 response body type for a given path + method. */
export type CreatedBody<
    P extends keyof paths,
    M extends keyof paths[P],
> = paths[P][M] extends {
    responses: { 201: { content: { 'application/json': infer R } } }
}
    ? R
    : never

/** Shorthand for schema components */
export type Schema<K extends keyof components['schemas']> =
    components['schemas'][K]
